packages:
  - 'packages/*'
  - 'apps/*'

shared-workspace-file:
  - pnpm-lock.yaml
  - .npmrc

resolutions:
  react: '18.2.0'
  react-dom: '18.2.0'
  vite: '^5.0.0'

install:
  autoInstallPeers: true
  dedupePeerDependencies: true
